# Position and orientation of rigid bodies

Define functions to work with rigid bodies

## Import functions needed

In [21]:
import numpy as np
import math

## Rotational matrix
Given an angle $\theta$ and a vector $r$, return a rotational matrix of the angle $\theta$ around the vector $r$.

In [22]:
def rotational(theta, r):
    # Separate x, y and z from vector r
    rx = r.item(0)
    ry = r.item(1)
    rz = r.item(2)
    
    # Calculate sin an cos of theta
    s = math.sin(theta)
    c = math.cos(theta)
    
    # Calculate rotational matrix
    rot = np.matrix([[rx*rx*(1-c)+c,    rx*ry*(1-c)-rz*s, rx*rz*(1-c)+ry*s],
                     [rx*ry*(1-c)+rz*s, ry*ry*(1-c)+c,    ry*rz*(1-c)-rx*s],
                     [rx*rz*(1-c)-ry*s, ry*rz*(1-c)+rx*s, rz*rz*(1-c)+c   ]])
    
    return rot

### Example
Rotational matrix of $\Pi$ around the vector $z$.

In [53]:
theta = math.pi
r = np.matrix([0,0,1])
R = rotational(theta, r)
print(R)

[[ -1.00000000e+00  -1.22464680e-16   0.00000000e+00]
 [  1.22464680e-16  -1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


## Inverse of rotational matrix
Given a rotational matrix $R$, return a unit vector $r$ and an angle $\theta$.

In [78]:
def inv_rotational(R):
    # Calculate R - R'
    RRt = R - np.transpose(R)
    
    # Calculate the trace the the matrix R
    trace = np.trace(R)
    
    # Calculate theta
    theta = math.atan2(math.sqrt(RRt.item(0,1)*RRt.item(0,1) +
                                 RRt.item(0,2)*RRt.item(0,2) +
                                 RRt.item(1,2)*RRt.item(1,2)), trace - 1)
    
    if (math.sin(theta) == 0):
        if theta == 0:
            raise Exception('ERROR: theta needs to be different than 0!')
        elif math.abs(theta) == math.pi:
            r = np.matrix([math.sqrt((R.item(0,0)+1)/2), math.sqrt((R.item(1,1)+1)/2), math.sqrt((R.item(2,2)+1)/2)])
            %TODO Correct signs
            raise Exception('Implement singular case!')
        
    # Calculate the unit vector r
    r = 1/(2*math.sin(theta))*np.matrix([-RRt.item(1,2), RRt.item(0,2), -RRt.item(0,1)])
    
    return [theta, r]

### Example
Recover the angle $\Pi$ and the vector $z$ given a rotational matrix $R$.

In [58]:
[theta, r] = inv_rotational(R)
print(theta)
print(r)

3.141592653589793
[[ 0.  0.  1.]]


## Check if $R$ is a rotational matrix
Return $True$ if matrix $R$ has the following properties to be rotational:
* Determinant equal to +1
* Its inverse is equal to its transpose

In [75]:
def is_rotational(R):
    # Check if R is ortogonal an
    if np.array_equal(np.transpose(R), np.linalg.inv(R)) and \
        np.linalg.det(R) == 1:
        return True

is_rotational(R)

True